language: node_js
node_js:
  - "6"
  - "7"

cache:
  directories:
    - ${HOME}/.npm
    - node_modules

before_install:
  - npm config set spin=false
  - npm install -g npm@4

install:
  - npm install

script:
  - npm run testonly

# Allow Travis tests to run in containers.
sudo: false
